# Generated by Django 4.2.5 on 2023-09-12 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('labtest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('othernames', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(db_index=True, max_length=255, null=True, unique=True)),
                ('phone', models.IntegerField(null=True)),
                ('sex', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer Not To Say', 'Prefer Not To Say')], max_length=200, null=True)),
                ('referralsname', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateTimeField(max_length=200, null=True)),
                ('staff_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeoftest', models.CharField(blank=True, choices=[('Blood Count Tests', 'Blood Count Tests'), ('Genetic Testing', 'Genetic Testing'), ('Kidney Tests', 'Kidney Tests'), ('Laboratory Tests', 'Laboratory Tests'), ('Prenatal Testing', 'Prenatal Testing'), ('Thyroid Tests', 'Thyroid Tests'), ('Urinalysis', 'Urinalysis')], max_length=200, null=True)),
                ('clinicaldiagnosis', models.CharField(blank=True, max_length=200, null=True)),
                ('natureofspecimen', models.CharField(blank=True, max_length=200, null=True)),
                ('typesofinvestigation', models.CharField(blank=True, max_length=200, null=True)),
                ('bloodgroup', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=200, null=True)),
                ('genotype', models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS')], max_length=200, null=True)),
                ('rvs', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateTimeField(max_length=200)),
                ('customername', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labtest.customer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
